In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

2022-02-14 14:58:25.077702: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [9]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()


2022-02-14 14:59:26.741448: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-14 14:59:26.742462: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-02-14 14:59:26.742610: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-14 14:59:26.742702: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lucas-Lenovo-ideapad-320-15IKB): /proc/driver/nvidia/version does not exist
2022-02-14 14:59:26.744616: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operat

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_images, train_labels, epochs=5)

2022-02-14 15:00:21.562666: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 188160000 exceeds 10% of free system memory.
2022-02-14 15:00:22.132106: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-02-14 15:00:22.245185: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2699905000 Hz


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6345 - accuracy: 0.7782
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3830 - accuracy: 0.8610
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3387 - accuracy: 0.8789
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3133 - accuracy: 0.8846
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2920 - accuracy: 0.8908


In [13]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

 56/313 [====>.........................] - ETA: 0s - loss: 0.3218 - accuracy: 0.8845 

2022-02-14 15:00:44.507734: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 31360000 exceeds 10% of free system memory.


313/313 [==============================] - 0s 951us/step - loss: 0.3573 - accuracy: 0.8745
Test accuracy: 0.8744999766349792


In [14]:
predictions = model.predict(test_images)

2022-02-14 15:01:10.122719: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 31360000 exceeds 10% of free system memory.


In [15]:
predictions[0]

array([1.0746136e-05, 1.4282341e-08, 9.1860267e-07, 4.5159419e-07,
       4.3818982e-06, 1.5510191e-03, 1.4399233e-06, 4.9464259e-02,
       4.2173106e-06, 9.4896257e-01], dtype=float32)

In [16]:
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [18]:
img = test_images[0]

print(img.shape)

(28, 28)


In [19]:
img = (np.expand_dims(img,0))

print(img.shape)


(1, 28, 28)


In [20]:
predictions_single = model.predict(img)

print(predictions_single)


[[1.0746136e-05 1.4282341e-08 9.1860267e-07 4.5159419e-07 4.3818941e-06
  1.5510191e-03 1.4399233e-06 4.9464259e-02 4.2173106e-06 9.4896257e-01]]


In [21]:
np.argmax(predictions_single[0])

9